---
title: "STAT 4000 HW 3"
output: html_notebook
---


```{r}
library(readxl)
LogitData <- read_excel("C:/Users/benja/Downloads/LogitData.xlsx")
```


USE THIS MODEL: P(y|x) = 1 / 1 + e ^ -(B0+B1X)

1. Fit the model IE: Find the parameters

```{r}
# --- cheat way he told us not to do after I'd already done it ---
general <- glm(y ~ x, data = LogitData, family = binomial(link = "logit"))

# --- "Real Man's Way!!" ---
# Intercept?
Bo = 1
# Slopey slope
Ba = -2
# X Values(duh)
x  = LogitData$x
# Told Model
Model <- function(x, i, c) {
    P = 1/(1+(exp(-(i + c * x))))
    return(P)
}

simulation <- function(i,c,n) {
    i = 1
    c = -100
    z = numeric(n)
    for(i in 1:n) {
        z[i] = Model(x[i], i, c)
    }
}


# -- Question Numbero Doso --

#PredictionY = Model(-3); PredictionY

# -- Board Notes --
i = 1
c = .5
z = numeric(100)
for(i in 1:100) {
    z[i] = Model(x[i], i, c)
}
plot(x, LogitData$y)
points(x, z, col = "red")





```


2. Predict y = 1 or y = 0 for an observation in x = -3

```{r}
xbar = data.frame("x" = -3)
#predict(general, newdata = xbar, type = "response")
y <- predict.glm(general, newdata = xbar, type = "response")

predict <- predict(general, type = "response")

```

*******************************************
# Principle of Maximum likelyhood
*******************************************

```{r}
plot(LogitData)


plot(LogitData$x, LogitData$y)

plot(general)

plot(predict)


library(ggplot2)

ggplot(general, aes(x = x, y = y)) + geom_point() +
    stat_smooth(method = "glm", method.args = list(family="binomial"), se= FALSE)

```

